#!/usr/bin/env python3

import json
import subprocess
import sys
import re
from monplugin import Check, Status


class CheckHurl:
    def __init__(self, hurlfile):
        self.hurlfile = hurlfile
        self.lines = open(hurlfile, encoding='UTF-8').readlines()
        self.json = None
        self.assert_status = 0
        self.check = Check("HURL")

    def run(self):
        cmd = ["hurl", "--json", self.hurlfile]
        check = self.check
        proc = subprocess.Popen(
            cmd,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            encoding='UTF-8'
        )
        stdout, stderr = proc.communicate()
        rc = proc.returncode

        if rc == self.EXIT_OK:
            check.exit(Status.OK, f"All assertions passed in {self.hurlfile}")
        elif rc == self.EXIT_ERROR_COMMANDLINE:
            check.exit(
                Status.UNKNOWN,
                "\n".join(["Something wrong with the command line", cmd]),
            )
        elif rc == self.EXIT_ERROR_PARSING:
            check.exit(
                Status.UNKNOWN,
                "\n".join(["Something wrong parsing file", stderr.replace("|", "\u2758")])
            )
        elif rc == self.EXIT_ERROR_RUNTIME:
            check.exit(Status.UNKNOWN, "\n".join(["Runtime error", stderr.replace("|", "\u2758")]))
        elif rc == self.EXIT_ERROR_ASSERT:
            self.json = json.loads(stdout)
            self._handle_assertion_error(stderr)
        else:
            check.exit(
                Status.UNKNOWN,
                "\n".join(["unknown error", stderr, str(proc.returncode)]),
            )

    def _update_assert_status(self, status):
        if status > self.assert_status:
            self.assert_status = status

    def _get_assert_criticality(self, line):
        line = self.lines[line - 1]
        match = re.search(self.RE_CRITICALITY, line)
        if match:
            severity = match.group(1)
            severity = getattr(Status, severity.upper(), Status.CRITICAL)
            return severity

        return Status.CRITICAL

    def _handle_assertion_error(self, stderr):
        self.check.add_message(Status.OK, "")

        for entry in self.json.get("entries", []):
            for claim in entry.get("asserts", []):
                severity = self._get_assert_criticality(claim["line"])
                if not claim["success"]:
                    self.check.add_message(severity, "")

        severity = self.check.check_messages()[0]
        if severity.value > 0:
            self.check.exit(
                severity,
                f"Assertions failed in { self.hurlfile }\n" + stderr.replace("|", "\u2758"),
            )
        else:
            self.check.exit(severity, "All assertions ok")

    EXIT_OK = 0
    EXIT_ERROR_COMMANDLINE = 1
    EXIT_ERROR_PARSING = 2
    EXIT_ERROR_RUNTIME = 3
    EXIT_ERROR_ASSERT = 4
    EXIT_ERROR_UNDEFINED = 127

    RE_CRITICALITY = r'#[^#"]*severity:(\w+)[^#"]*$'


if __name__ == "__main__":
    CheckHurl(sys.argv[1]).run()
